### ISSUE TITLE
debian/raspad-launcher/bin/raspad-launcher changed mode to non executable

### ISSUE THREAD

**Issue by purewasa** [raspad-tablet/raspad-launcher#4]
Hi @cavonlee, hi @sunfounder 

your recent commit https://github.com/raspad-tablet/raspad-launcher/commit/37abd584281c25835db2569e3a73e135e002d62d changed the file mode of the readily built raspad-launcher executable to be non-executable file!:

diff --git a/debian/raspad-launcher/bin/raspad-launcher b/debian/raspad-launcher/bin/raspad-launcher
old mode 100755
new mode 100644

Did you intend that? Or is it a mistake?

**Comment by sunfounder** [comment]
Hi @purewasa 
It's not intended but it's ok, as the install script will add executable to the file. see [here](https://github.com/raspad-tablet/raspad-launcher/blob/d861e6bbae3c2f7fece88061c0fd4477afc575dd/debian/raspad-launcher/install#L70).

**Comment by purewasa** [comment]
Hi @sunfounder,

then it is ok for me. I just wanted you to notice.
